"""
PSADT Package Builder
- Reads and validates a user-supplied PSADT template
- Generates a fully-populated Deploy-Application.ps1
- Builds the standard PSADT folder structure
Supports: EXE, MSI, MSIX installers
"""

import re
import shutil
from pathlib import Path
from typing import Optional
from dataclasses import dataclass, field

from utils import get_logger, sanitize_app_name, timestamp_slug
from config import PACKAGES_DIR, PSADT_VERSION

log = get_logger("psadt-template")

# ---------------------------------------------------------------------------
# Data model for package parameters
# ---------------------------------------------------------------------------
@dataclass
class PackageSpec:
    app_name: str
    app_version: str
    app_vendor: str
    installer_path: str          # absolute path to installer file
    installer_type: str          # EXE | MSI | MSIX
    silent_switches: str         # e.g. /quiet /norestart
    # Optional
    architecture: str = "x64"
    install_location: Optional[str] = None
    dependencies: list[str] = field(default_factory=list)
    pre_install_commands: list[str] = field(default_factory=list)
    post_install_commands: list[str] = field(default_factory=list)
    uninstall_product_code: Optional[str] = None  # GUID for MSI
    custom_uninstall_string: Optional[str] = None
    psadt_version: str = PSADT_VERSION
    # Populated after build
    package_dir: Optional[str] = None
    script_path: Optional[str] = None


# ---------------------------------------------------------------------------
# Folder structure builder
# ---------------------------------------------------------------------------
def build_package_structure(spec: PackageSpec, template_path: str, output_base: Optional[str] = None) -> str:
    """
    Copy the PSADT template to a new package folder and inject the installer.
    Returns the path to the new package directory.
    """
    safe_name = sanitize_app_name(spec.app_name)
    safe_ver  = sanitize_app_name(spec.app_version)
    slug      = timestamp_slug()
    out_base  = Path(output_base) if output_base else PACKAGES_DIR
    pkg_dir   = out_base / f"{safe_name}_{safe_ver}_{slug}"

    template = Path(template_path)
    if not template.exists():
        raise FileNotFoundError(f"PSADT template not found: {template_path}")

    log.info(f"Copying PSADT template → {pkg_dir}")
    shutil.copytree(str(template), str(pkg_dir), dirs_exist_ok=False)

    # Copy installer into the Files subfolder
    files_dir = pkg_dir / "Files"
    files_dir.mkdir(exist_ok=True)
    installer_src = Path(spec.installer_path)
    if installer_src.exists():
        shutil.copy2(str(installer_src), str(files_dir / installer_src.name))
        log.info(f"Installer copied → {files_dir / installer_src.name}")
    else:
        log.warning(f"Installer not found at {spec.installer_path} — skipping copy")

    spec.package_dir = str(pkg_dir)
    return str(pkg_dir)


# ---------------------------------------------------------------------------
# Deploy-Application.ps1 generator
# ---------------------------------------------------------------------------
def generate_deploy_script(spec: PackageSpec) -> str:
    """
    Return the full text of a Deploy-Application.ps1 tailored to the PackageSpec.
    Follows PSADT v3.x conventions (supports 3.8–3.10.x).
    """
    safe_name = spec.app_name.replace("'", "''")
    safe_ver  = spec.app_version.replace("'", "''")
    safe_vendor = spec.app_vendor.replace("'", "''")
    installer_filename = Path(spec.installer_path).name

    # Build install command block
    install_block = _build_install_block(spec, installer_filename)
    # Build uninstall block (cleanup of previous versions)
    uninstall_block = _build_uninstall_block(spec)
    # Pre/post install extras
    pre_cmds  = "\n".join(f"\t\tExecute-Process -Path 'cmd.exe' -Parameters '/c {c}' -WindowStyle Hidden" for c in spec.pre_install_commands)
    post_cmds = "\n".join(f"\t\tExecute-Process -Path 'cmd.exe' -Parameters '/c {c}' -WindowStyle Hidden" for c in spec.post_install_commands)
    dep_notes = "\n".join(f"\t\t## Dependency: {d}" for d in spec.dependencies) if spec.dependencies else "\t\t## No additional dependencies"

    script = f'''\
<#
.SYNOPSIS
    PSADT Deploy-Application.ps1 — Auto-generated by PSADT Agentic AI
    App     : {spec.app_name} {spec.app_version}
    Vendor  : {spec.app_vendor}
    Type    : {spec.installer_type}
    Created : $(Get-Date -Format 'yyyy-MM-dd HH:mm')
.NOTES
    PowerShell App Deployment Toolkit v{spec.psadt_version}
    https://psappdeploytoolkit.com
#>

[CmdletBinding()]
Param (
    [Parameter(Mandatory = $false)]
    [ValidateSet('Install','Uninstall','Repair')]
    [string]$DeploymentType = 'Install',
    [Parameter(Mandatory = $false)]
    [ValidateSet('Interactive','Silent','NonInteractive')]
    [string]$DeployMode = 'NonInteractive',
    [Parameter(Mandatory = $false)]
    [switch]$AllowRebootPassThru = $false,
    [Parameter(Mandatory = $false)]
    [switch]$TerminalServerMode = $false,
    [Parameter(Mandatory = $false)]
    [switch]$DisableLogging = $false
)

## ---------------------------------------------------------------------------
## VARIABLES
## ---------------------------------------------------------------------------
[string]$appVendor        = '{safe_vendor}'
[string]$appName          = '{safe_name}'
[string]$appVersion       = '{safe_ver}'
[string]$appArch          = '{spec.architecture}'
[string]$appLang          = 'EN'
[string]$appRevision      = '01'
[string]$appScriptVersion = '1.0.0'
[string]$appScriptDate    = (Get-Date -Format 'MM/dd/yyyy')
[string]$appScriptAuthor  = 'PSADT Agentic AI'

## Suppress ALL reboot actions
$global:AllowRebootPassThru = $false

## ---------------------------------------------------------------------------
## TOOLKIT INIT
## ---------------------------------------------------------------------------
Try {{
    [string]$scriptDirectory = Split-Path -Parent $MyInvocation.MyCommand.Definition
    . "$scriptDirectory\\AppDeployToolkit\\AppDeployToolkitMain.ps1"
}}
Catch {{
    [int32]$mainExitCode = 60008
    Write-Error -Message "[$appName] Failed to import AppDeployToolkitMain.ps1: $_" -ErrorAction 'Continue'
    Exit $mainExitCode
}}

## ---------------------------------------------------------------------------
## INSTALLATION
## ---------------------------------------------------------------------------
If ($deploymentType -ine 'Uninstall' -and $deploymentType -ine 'Repair') {{

    ## ---- PRE-INSTALLATION ------------------------------------------------
    [string]$installPhase = 'Pre-Installation'
    Write-Log -Message "[$installPhase] Starting $appName $appVersion" -Source $installPhase

    ## Close conflicting processes (add as needed)
    # Show-InstallationWelcome -CloseApps 'processname' -Silent -AllowDefer -DeferTimes 3

    ## Show progress silently
    Show-InstallationProgress -StatusMessage "Installing $appName $appVersion. Please wait..."

    ## CLEANUP: Remove any previously installed version of the application
    Write-Log -Message "[$installPhase] Checking for existing installations to remove..." -Source $installPhase
{uninstall_block}

    ## Dependency notes
{dep_notes}
{pre_cmds}

    ## ---- INSTALLATION ----------------------------------------------------
    [string]$installPhase = 'Installation'
    Write-Log -Message "[$installPhase] Installing $appName $appVersion" -Source $installPhase

{install_block}

    ## ---- POST-INSTALLATION -----------------------------------------------
    [string]$installPhase = 'Post-Installation'
    Write-Log -Message "[$installPhase] Completing $appName $appVersion setup" -Source $installPhase

{post_cmds}

    ## Suppress all reboots
    Set-RegistryKey -Key 'HKLM:SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WindowsUpdate\\Auto Update' `
                    -Name 'RebootRequired' -Value 0 -Type DWord -ErrorAction SilentlyContinue
    Write-Log -Message "[$installPhase] Installation of $appName $appVersion completed." -Source $installPhase

}} ElseIf ($deploymentType -ieq 'Uninstall') {{

    ## ---- UNINSTALLATION --------------------------------------------------
    [string]$installPhase = 'Uninstallation'
    Write-Log -Message "[$installPhase] Uninstalling $appName" -Source $installPhase

    Show-InstallationProgress -StatusMessage "Uninstalling $appName. Please wait..."

{uninstall_block}

    Write-Log -Message "[$installPhase] Uninstallation of $appName completed." -Source $installPhase

}} ElseIf ($deploymentType -ieq 'Repair') {{

    ## ---- REPAIR ----------------------------------------------------------
    [string]$installPhase = 'Repair'
    Write-Log -Message "[$installPhase] Repairing $appName $appVersion" -Source $installPhase

{install_block}

}}

## ---------------------------------------------------------------------------
## FINALIZATION
## ---------------------------------------------------------------------------
Exit-Script -ExitCode $mainExitCode
'''
    return script


def _build_install_block(spec: PackageSpec, installer_filename: str) -> str:
    itype = spec.installer_type.upper()

    if itype == "MSI":
        return f"""\
    ## MSI Installation — all users, no reboot
    Execute-MSI -Action Install `
                -Path "$dirFiles\\{installer_filename}" `
                -Parameters '{spec.silent_switches} ALLUSERS=1 REBOOT=ReallySuppress' `
                -PassThru"""

    elif itype == "MSIX":
        return f"""\
    ## MSIX / AppX Installation
    Execute-Process -Path 'PowerShell.exe' `
                    -Parameters '-NonInteractive -NoProfile -Command "Add-AppxProvisionedPackage -Online -PackagePath \\"$dirFiles\\{installer_filename}\\" -SkipLicense"' `
                    -WindowStyle Hidden -PassThru"""

    else:  # EXE (default)
        return f"""\
    ## EXE Silent Installation — all users, no reboot
    Execute-Process -Path "$dirFiles\\{installer_filename}" `
                    -Parameters '{spec.silent_switches}' `
                    -WindowStyle Hidden `
                    -PassThru"""


def _build_uninstall_block(spec: PackageSpec) -> str:
    safe_name = spec.app_name.replace("'", "''")

    if spec.uninstall_product_code:
        # MSI product code known
        guid = spec.uninstall_product_code
        return f"""\
    ## Uninstall previous MSI version by product code (any version)
    [array]$installedVersions = Get-InstalledApplication -Name '{safe_name}'
    ForEach ($app in $installedVersions) {{
        If ($app.UninstallSubkey) {{
            Write-Log -Message "Removing previous version: $($app.DisplayName) $($app.DisplayVersion)" -Source $installPhase
            Execute-MSI -Action Uninstall -Path $app.UninstallSubkey `
                        -Parameters '/quiet /norestart REBOOT=ReallySuppress'
        }}
    }}
    ## Also attempt direct product code removal
    Execute-MSI -Action Uninstall -Path '{guid}' `
                -Parameters '/quiet /norestart REBOOT=ReallySuppress' `
                -ErrorAction SilentlyContinue"""

    elif spec.custom_uninstall_string:
        uninstall_cmd = spec.custom_uninstall_string.replace("'", "''")
        return f"""\
    ## Uninstall previous version via known uninstall string
    [array]$installedVersions = Get-InstalledApplication -Name '{safe_name}'
    ForEach ($app in $installedVersions) {{
        Write-Log -Message "Removing previous version: $($app.DisplayName) $($app.DisplayVersion)" -Source $installPhase
        Execute-Process -Path 'cmd.exe' `
                        -Parameters '/c "{uninstall_cmd}"' `
                        -WindowStyle Hidden -ErrorAction SilentlyContinue
    }}"""

    else:
        # Generic — query registry and attempt quiet uninstall
        return f"""\
    ## Generic cleanup: uninstall any existing version of '{safe_name}'
    [array]$installedVersions = Get-InstalledApplication -Name '{safe_name}'
    ForEach ($app in $installedVersions) {{
        Write-Log -Message "Removing existing version: $($app.DisplayName) $($app.DisplayVersion)" -Source $installPhase
        If ($app.UninstallString -like 'msiexec*') {{
            ## MSI uninstall
            $productCode = $app.UninstallSubkey
            Execute-MSI -Action Uninstall -Path $productCode `
                        -Parameters '/quiet /norestart REBOOT=ReallySuppress'
        }} ElseIf ($app.QuietUninstallString) {{
            ## EXE quiet uninstall string provided
            $exePath   = ($app.QuietUninstallString -split '"')[1]
            $exeParams = ($app.QuietUninstallString -split '"',3)[2].Trim()
            Execute-Process -Path $exePath -Parameters $exeParams `
                            -WindowStyle Hidden -ErrorAction SilentlyContinue
        }} ElseIf ($app.UninstallString) {{
            ## Attempt silent flag on raw uninstall string
            $exePath = ($app.UninstallString -split '"')[1]
            Execute-Process -Path $exePath -Parameters '/S /silent /quiet' `
                            -WindowStyle Hidden -ErrorAction SilentlyContinue
        }}
    }}"""


# ---------------------------------------------------------------------------
# WSB config generator (Windows Sandbox)
# ---------------------------------------------------------------------------
def generate_wsb_config(package_dir: str, script_name: str = "Deploy-Application.ps1") -> str:
    """Generate a .wsb file to test the package inside Windows Sandbox."""
    pkg_path = Path(package_dir)
    wsb = f"""<Configuration>
  <MappedFolders>
    <MappedFolder>
      <HostFolder>{pkg_path}</HostFolder>
      <SandboxFolder>C:\\PSADTPackage</SandboxFolder>
      <ReadOnly>false</ReadOnly>
    </MappedFolder>
  </MappedFolders>
  <LogonCommand>
    <Command>PowerShell.exe -NonInteractive -NoProfile -ExecutionPolicy Bypass -File "C:\\PSADTPackage\\{script_name}" -DeploymentType Install -DeployMode Silent</Command>
  </LogonCommand>
  <ProtectedClient>false</ProtectedClient>
  <Networking>Default</Networking>
</Configuration>
"""
    wsb_path = pkg_path / "sandbox_test.wsb"
    wsb_path.write_text(wsb, encoding="utf-8")
    log.info(f"WSB config written → {wsb_path}")
    return str(wsb_path)
