"""
PSADT v4 Package Builder
- Copies the v4 template to C:/Temp/Packages/<AppName_Version_Slug>/
- Places the installer in the Files/ subfolder
- Generates a populated Invoke-AppDeployToolkit.ps1 using v4 ADT cmdlets
"""

import re
import shutil
from pathlib import Path
from typing import Optional
from dataclasses import dataclass, field

from utils import get_logger, sanitize_app_name, timestamp_slug, validate_package_path
from config import PACKAGES_DIR, PSADT_VERSION

log = get_logger("psadt-template")


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------
@dataclass
class PackageSpec:
    app_name: str
    app_version: str
    app_vendor: str
    installer_path: str
    installer_type: str          # EXE | MSI | MSIX
    silent_switches: str
    architecture: str = "x64"
    install_location: Optional[str] = None
    dependencies: list = field(default_factory=list)
    pre_install_commands: list = field(default_factory=list)
    post_install_commands: list = field(default_factory=list)
    uninstall_product_code: Optional[str] = None
    custom_uninstall_string: Optional[str] = None
    psadt_version: str = PSADT_VERSION
    package_dir: Optional[str] = None
    script_path: Optional[str] = None


# ---------------------------------------------------------------------------
# Folder structure builder
# ---------------------------------------------------------------------------
_ALLOWED_INSTALLER_EXTENSIONS = {".exe", ".msi", ".msix", ".msp", ".msu", ".appx"}


def build_package_structure(spec: PackageSpec, template_path: str, output_base: Optional[str] = None) -> str:
    """
    Copy PSADT v4 template to C:\\Temp\\Packages\\<AppName_Version_Slug>
    and place the installer in the Files\\ subfolder.
    Returns the path to the new package directory.
    """
    safe_name = sanitize_app_name(spec.app_name)
    safe_ver  = sanitize_app_name(spec.app_version)
    slug      = timestamp_slug()
    out_base  = Path(output_base) if output_base else PACKAGES_DIR
    pkg_dir   = out_base / f"{safe_name}_{safe_ver}_{slug}"

    # --- Validate package destination path ---
    validate_package_path(pkg_dir, out_base)

    # --- Validate template ---
    template = Path(template_path)
    if not template.exists():
        raise FileNotFoundError(f"PSADT template not found: {template_path}")
    if not template.is_dir():
        raise ValueError(f"Template path is not a directory: {template_path}")

    # --- Validate installer source ---
    installer_src = Path(spec.installer_path)
    if not installer_src.exists():
        raise FileNotFoundError(f"Installer not found: {spec.installer_path}")
    if not installer_src.is_file():
        raise ValueError(f"Installer path is not a file: {spec.installer_path}")
    if installer_src.suffix.lower() not in _ALLOWED_INSTALLER_EXTENSIONS:
        raise ValueError(
            f"Unsupported installer type '{installer_src.suffix}'. "
            f"Allowed: {', '.join(sorted(_ALLOWED_INSTALLER_EXTENSIONS))}"
        )

    log.info(f"Copying PSADT v4 template → {pkg_dir}")
    shutil.copytree(str(template), str(pkg_dir), dirs_exist_ok=False)

    # Place installer in Files\
    files_dir = pkg_dir / "Files"
    files_dir.mkdir(exist_ok=True)
    shutil.copy2(str(installer_src), str(files_dir / installer_src.name))
    log.info(f"Installer copied → {files_dir / installer_src.name}")

    spec.package_dir = str(pkg_dir)
    return str(pkg_dir)


# ---------------------------------------------------------------------------
# Invoke-AppDeployToolkit.ps1 generator (PSADT v4)
# ---------------------------------------------------------------------------
def generate_deploy_script(spec: PackageSpec) -> str:
    """
    Return the full text of a PSADT v4 Invoke-AppDeployToolkit.ps1
    populated with install, uninstall, and repair logic for the given spec.
    """
    safe_vendor  = spec.app_vendor.replace("'", "''")
    safe_name    = spec.app_name.replace("'", "''")
    safe_ver     = spec.app_version.replace("'", "''")
    installer_fn = Path(spec.installer_path).name

    install_block   = _build_install_block(spec, installer_fn)
    uninstall_block = _build_uninstall_block(spec)
    repair_block    = _build_repair_block(spec, installer_fn)

    pre_cmds  = "\n".join(
        f"    Start-ADTProcess -FilePath 'cmd.exe' -ArgumentList '/c {c}' -WindowStyle Hidden"
        for c in spec.pre_install_commands
    )
    post_cmds = "\n".join(
        f"    Start-ADTProcess -FilePath 'cmd.exe' -ArgumentList '/c {c}' -WindowStyle Hidden"
        for c in spec.post_install_commands
    )

    script = f'''\
<#
.SYNOPSIS
    PSAppDeployToolkit - This script performs the installation or uninstallation of an application(s).

.DESCRIPTION
    Auto-generated by PSADT Agentic AI
    App    : {spec.app_name} {spec.app_version}
    Vendor : {spec.app_vendor}
    Type   : {spec.installer_type}

.LINK
    https://psappdeploytoolkit.com
#>

[CmdletBinding()]
param
(
    [Parameter(Mandatory = $false)]
    [ValidateSet('Install', 'Uninstall', 'Repair')]
    [System.String]$DeploymentType,

    [Parameter(Mandatory = $false)]
    [ValidateSet('Auto', 'Interactive', 'NonInteractive', 'Silent')]
    [System.String]$DeployMode,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$SuppressRebootPassThru,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$TerminalServerMode,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$DisableLogging
)


##================================================
## MARK: Variables
##================================================

$adtSession = @{{
    AppVendor            = '{safe_vendor}'
    AppName              = '{safe_name}'
    AppVersion           = '{safe_ver}'
    AppArch              = '{spec.architecture}'
    AppLang              = 'EN'
    AppRevision          = '01'
    AppSuccessExitCodes  = @(0)
    AppRebootExitCodes   = @(1641, 3010)
    AppProcessesToClose  = @()
    AppScriptVersion     = '1.0.0'
    AppScriptDate        = '{__import__("datetime").date.today()}'
    AppScriptAuthor      = 'PSADT Agentic AI'
    RequireAdmin         = $true
    InstallName          = ''
    InstallTitle         = ''
    DeployAppScriptFriendlyName = $MyInvocation.MyCommand.Name
    DeployAppScriptParameters   = $PSBoundParameters
    DeployAppScriptVersion      = '4.1.8'
}}


function Install-ADTDeployment
{{
    [CmdletBinding()]
    param()

    ##================================================
    ## MARK: Pre-Install
    ##================================================
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"

    ## Close running processes if any are defined above in AppProcessesToClose
    $saiwParams = @{{ AllowDefer = $true; DeferTimes = 3; CheckDiskSpace = $true; PersistPrompt = $true }}
    if ($adtSession.AppProcessesToClose.Count -gt 0) {{ $saiwParams.Add('CloseProcesses', $adtSession.AppProcessesToClose) }}
    Show-ADTInstallationWelcome @saiwParams
    Show-ADTInstallationProgress

    ## Remove any previously installed version
{uninstall_block}

{pre_cmds}

    ##================================================
    ## MARK: Install
    ##================================================
    $adtSession.InstallPhase = $adtSession.DeploymentType

{install_block}

    ##================================================
    ## MARK: Post-Install
    ##================================================
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"

{post_cmds}
}}


function Uninstall-ADTDeployment
{{
    [CmdletBinding()]
    param()

    ##================================================
    ## MARK: Pre-Uninstall
    ##================================================
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"

    if ($adtSession.AppProcessesToClose.Count -gt 0)
    {{
        Show-ADTInstallationWelcome -CloseProcesses $adtSession.AppProcessesToClose -CloseProcessesCountdown 60
    }}
    Show-ADTInstallationProgress

    ##================================================
    ## MARK: Uninstall
    ##================================================
    $adtSession.InstallPhase = $adtSession.DeploymentType

{uninstall_block}

    ##================================================
    ## MARK: Post-Uninstall
    ##================================================
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"
}}


function Repair-ADTDeployment
{{
    [CmdletBinding()]
    param()

    ##================================================
    ## MARK: Pre-Repair
    ##================================================
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"

    if ($adtSession.AppProcessesToClose.Count -gt 0)
    {{
        Show-ADTInstallationWelcome -CloseProcesses $adtSession.AppProcessesToClose -CloseProcessesCountdown 60
    }}
    Show-ADTInstallationProgress

    ##================================================
    ## MARK: Repair
    ##================================================
    $adtSession.InstallPhase = $adtSession.DeploymentType

{repair_block}

    ##================================================
    ## MARK: Post-Repair
    ##================================================
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"
}}


##================================================
## MARK: Initialization
##================================================

$ErrorActionPreference = [System.Management.Automation.ActionPreference]::Stop
$ProgressPreference    = [System.Management.Automation.ActionPreference]::SilentlyContinue
Set-StrictMode -Version 1

try
{{
    if (Test-Path -LiteralPath "$PSScriptRoot\\PSAppDeployToolkit\\PSAppDeployToolkit.psd1" -PathType Leaf)
    {{
        Get-ChildItem -LiteralPath "$PSScriptRoot\\PSAppDeployToolkit" -Recurse -File | Unblock-File -ErrorAction Ignore
        Import-Module -FullyQualifiedName @{{ ModuleName = "$PSScriptRoot\\PSAppDeployToolkit\\PSAppDeployToolkit.psd1"; Guid = '8c3c366b-8606-4576-9f2d-4051144f7ca2'; ModuleVersion = '4.1.8' }} -Force
    }}
    else
    {{
        Import-Module -FullyQualifiedName @{{ ModuleName = 'PSAppDeployToolkit'; Guid = '8c3c366b-8606-4576-9f2d-4051144f7ca2'; ModuleVersion = '4.1.8' }} -Force
    }}

    $iadtParams  = Get-ADTBoundParametersAndDefaultValues -Invocation $MyInvocation
    $adtSession  = Remove-ADTHashtableNullOrEmptyValues -Hashtable $adtSession
    $adtSession  = Open-ADTSession @adtSession @iadtParams -PassThru
}}
catch
{{
    $Host.UI.WriteErrorLine((Out-String -InputObject $_ -Width ([System.Int32]::MaxValue)))
    exit 60008
}}


##================================================
## MARK: Invocation
##================================================

try
{{
    Get-ChildItem -LiteralPath $PSScriptRoot -Directory | & {{
        process
        {{
            if ($_.Name -match 'PSAppDeployToolkit\\..+$')
            {{
                Get-ChildItem -LiteralPath $_.FullName -Recurse -File | Unblock-File -ErrorAction Ignore
                Import-Module -Name $_.FullName -Force
            }}
        }}
    }}

    & "$($adtSession.DeploymentType)-ADTDeployment"
    Close-ADTSession
}}
catch
{{
    $mainErrorMessage = "An unhandled error within [$($MyInvocation.MyCommand.Name)] has occurred.`n$(Resolve-ADTErrorRecord -ErrorRecord $_)"
    Write-ADTLogEntry -Message $mainErrorMessage -Severity 3
    Close-ADTSession -ExitCode 60001
}}
'''
    return script


def _build_install_block(spec: PackageSpec, installer_fn: str) -> str:
    itype = spec.installer_type.upper()
    switches = spec.silent_switches.replace("'", "''")

    if itype == "MSI":
        return (
            f"    ## MSI silent install\n"
            f"    Start-ADTMsiProcess -Action Install "
            f"-FilePath \"$($adtSession.DirFiles)\\{installer_fn}\" "
            f"-ArgumentList '{switches} ALLUSERS=1 REBOOT=ReallySuppress'"
        )
    elif itype == "MSIX":
        return (
            f"    ## MSIX provisioned install\n"
            f"    Start-ADTProcess -FilePath 'PowerShell.exe' "
            f"-ArgumentList '-NonInteractive -NoProfile -Command "
            f"\"Add-AppxProvisionedPackage -Online -PackagePath \\\"$($adtSession.DirFiles)\\{installer_fn}\\\" -SkipLicense\"' "
            f"-WindowStyle Hidden"
        )
    else:  # EXE
        return (
            f"    ## EXE silent install\n"
            f"    Start-ADTProcess -FilePath \"$($adtSession.DirFiles)\\{installer_fn}\" "
            f"-ArgumentList '{switches}' -WindowStyle Hidden"
        )


def _build_uninstall_block(spec: PackageSpec) -> str:
    safe_name   = spec.app_name.replace("'", "''")
    safe_vendor = spec.app_vendor.replace("'", "''")
    app_type    = "MSI" if spec.installer_type.upper() == "MSI" else "EXE"

    return (
        f"    ## Remove any existing version of the application\n"
        f"    Uninstall-ADTApplication -Name '{safe_name}' -ApplicationType {app_type} "
        f"-FilterScript {{ $_.Publisher -match '{safe_vendor}' }}"
    )


def _build_repair_block(spec: PackageSpec, installer_fn: str) -> str:
    itype = spec.installer_type.upper()
    switches = spec.silent_switches.replace("'", "''")

    if itype == "MSI":
        return (
            f"    ## MSI repair\n"
            f"    Start-ADTMsiProcess -Action Repair "
            f"-FilePath \"$($adtSession.DirFiles)\\{installer_fn}\" "
            f"-ArgumentList '{switches} REBOOT=ReallySuppress'"
        )
    else:
        # EXE/MSIX: re-run installer as repair
        return _build_install_block(spec, installer_fn)


# ---------------------------------------------------------------------------
# WSB config generator (Windows Sandbox)
# ---------------------------------------------------------------------------
def generate_wsb_config(package_dir: str, script_name: str = "Invoke-AppDeployToolkit.ps1") -> str:
    pkg_path = Path(package_dir)
    wsb = f"""<Configuration>
  <MappedFolders>
    <MappedFolder>
      <HostFolder>{pkg_path}</HostFolder>
      <SandboxFolder>C:\\PSADTPackage</SandboxFolder>
      <ReadOnly>false</ReadOnly>
    </MappedFolder>
  </MappedFolders>
  <LogonCommand>
    <Command>PowerShell.exe -NonInteractive -NoProfile -ExecutionPolicy Bypass -File "C:\\PSADTPackage\\{script_name}" -DeploymentType Install -DeployMode Silent</Command>
  </LogonCommand>
  <ProtectedClient>false</ProtectedClient>
  <Networking>Default</Networking>
</Configuration>
"""
    wsb_path = pkg_path / "sandbox_test.wsb"
    wsb_path.write_text(wsb, encoding="utf-8")
    log.info(f"WSB config written → {wsb_path}")
    return str(wsb_path)
